
server:
  port : 8081

spring:
  datasource:
    url : jdbc:mysql://10.11.13.49:3306/test
    username : root
    password : password
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    database-platform : org.hibernate.dialect.MySQLDialect

jwt:
  secret : saleispower